import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';

const browser = await chromium.launch({ channel: 'msedge' });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on('console', message => { if (message.text().startsWith('Preview state')) console.log(message.text()); });
  page.on('pageerror', error => { errors.push(error.message); console.error('Browser:', error.message); });
  await page.goto('http://127.0.0.1:5173/');
  await page.getByRole('button', { name: 'Go trick-or-treating' }).waitFor({ timeout: 120000 });
  console.log('Title loaded; checking expansion engine');
  const results = await page.evaluate(async () => {
    const { Game } = await import('/src/game/engine.ts');
    const data = await import('/src/game/data.ts');
    const { expansion, hasFullGame } = await import('/src/game/expansion.ts');
    const { buildMap, cellAt, blockedCircle } = await import('/src/game/map.ts');
    const input = () => ({ keys: new Set(), pressed: new Set(), rpressed: false, mdown: false, mouseActive: false, wheel: 0, endFrame() { this.pressed.clear(); this.rpressed = false; this.wheel = 0; } });
    const save = () => ({ hero: 0, soul: 0, best: 0, talents: {} });
    const out = {};
    const free = new Game(4, save(), input(), true);
    out.locked = !free.campaign && free.hero === 0 && data.makeWeapon('gloom', 1).def.id === 'pea' && !hasFullGame();
    out.freeHouses = free.map.houses.length;
    expansion.preview();
    console.log('Preview state', JSON.stringify(expansion.snapshot()), hasFullGame());
    const controls = input(), g = new Game(3, save(), controls, true);
    out.intro = g.state === 'intro' && g.friends.length === 4 && !g.friends.some(f => f.hero === 3);
    out.expandedHouses = g.map.houses.length;
    g.introTime = 18; g.update(1 / 30);
    out.introEnds = g.state === 'play' && g.time === 0;
    // Open every gate through the real director; don't bypass collision.
    g.time = 245; g.p.invuln = 999;
    g.director(1 / 30);
    g.computeFlow(true);
    out.gates = g.map.gates.every(gate => gate.opened);
    out.reachableSites = g.friends.map(f => ({ hero: f.hero, free: cellAt(g.map, f.x, f.y) === 0, reachable: g.reachable(f.x, f.y) }));
    const f = g.friends[0];
    Object.assign(g.p, { x: f.x, y: f.y, hurtT: 0 }); g.computeFlow(true); g.updateTeam(1 / 30);
    out.guardian = f.status === 'waiting' && !!f.guardian;
    g.killEnemy(f.guardian);
    controls.keys.add('e');
    for (let i = 0; i < 95; i++) g.updateTeam(1 / 30);
    controls.keys.clear();
    out.rescued = f.status === 'rescued' && g.activeFriend === f.hero;
    g.state = 'pause';
    const playerUid = g.p.weapons[0].uid, friendUid = f.weapon.uid;
    g.giveFriendWeapon(f.hero, 0);
    out.swap = g.p.weapons[0].uid === friendUid && f.weapon.uid === playerUid;
    g.p.coins = 999; g.shopUpgrade(0);
    out.autoUpgrade = f.weapon.level === g.p.weapons[0].level;
    const second = g.friends[1]; second.status = 'rescued'; g.selectFriend(second.hero);
    out.singleHelper = g.activeFriend === second.hero;
    second.x = g.p.x; second.y = g.p.y; second.hurtCd = 0; g.enemies = []; g.ebullets = [];
    g.state = 'play'; g.p.hp = 1; g.p.shield = 0; g.p.invuln = 0; g.p.revives = 0;
    g.takeDamage(9999, g.p.x, g.p.y);
    out.downed = g.state === 'downed';
    for (let i = 0; i < 95; i++) g.updateTeam(1 / 30);
    out.revived = g.state === 'play' && g.p.hp > 0 && second.reviveCd > 0;
    g.pickups = [{ x: second.x, y: second.y, z: 0, vz: 0, vx: 0, vy: 0, kind: 'xp2', value: 0, mag: false, t: 0, dead: false, friendOnly: true }];
    const xp = g.p.xp; g.updatePickups(0.03);
    out.playerCantTakeFriendCandy = !g.pickups[0].dead && g.p.xp === xp;
    g.updateTeam(0.03); out.friendCandy = second.candy === 1 && g.pickups[0].dead;
    g.kills = 80; g.endRun(false); const paid = g.save.soul; g.endRun(false);
    out.onceOnlyReward = g.save.soul === paid && paid > 0;
    const counts = data.HERO_INFO.length;
    out.content = { kids: counts, guns: data.WEAPONS.length, costumes: data.COSTUMES.length, advancedTalents: data.TALENTS.filter(t => t.premium).length };
    out.mapRuns = 0;
    for (let hero = 0; hero < counts; hero++) for (let run = 0; run < 6; run++) {
      const candidate = new Game(hero, save(), input(), true, 1337 + run * 7919);
      if (blockedCircle(candidate.map, candidate.p.x, candidate.p.y, 0.5)) throw new Error('Unsafe player start');
      if (candidate.friends.some(friend => candidate.reachable(friend.x, friend.y))) throw new Error('Locked district can be reached before its gate opens');
      if (candidate.friends.length !== 4 || candidate.friends.some(f => f.hero === hero)) throw new Error('Invalid rescue roster');
      candidate.time = 245; candidate.director(0.03); candidate.computeFlow(true);
      for (const friend of candidate.friends) if (cellAt(candidate.map, friend.x, friend.y) !== 0 || !candidate.reachable(friend.x, friend.y)) throw new Error(`Unreachable rescue: hero ${hero}, run ${run}`);
      out.mapRuns++;
    }
    const saved = { soul: 500, best: 80, hero: 4, talents: { sharp: 2, heavy: 1 } };
    data.storeSave(saved); const restored = data.loadSave();
    out.saveRoundtrip = restored.soul === saved.soul && restored.best === saved.best && restored.hero === saved.hero && restored.talents.sharp === 2 && restored.talents.heavy === 1;
    return out;
  });
  console.log(JSON.stringify(results, null, 2));
  for (const key of ['locked', 'intro', 'introEnds', 'gates', 'guardian', 'rescued', 'swap', 'autoUpgrade', 'singleHelper', 'downed', 'revived', 'playerCantTakeFriendCandy', 'friendCandy', 'onceOnlyReward']) assert.equal(results[key], true, key);
  assert.ok(results.expandedHouses > results.freeHouses);
  assert.equal(results.saveRoundtrip, true);
  for (const site of results.reachableSites) assert.ok(site.free && site.reachable, `Rescue site ${site.hero} must be reachable`);
  await page.getByRole('button', { name: 'Go trick-or-treating' }).click();
  await page.waitForFunction(() => window.__tot?.game);
  await page.keyboard.press('i');
  await page.getByRole('dialog', { name: 'Run inventory' }).waitFor();
  await page.screenshot({ path: 'art/world/checks/run-inventory.png' });
  await page.getByRole('button', { name: 'Close inventory' }).click();
  await page.evaluate(() => window.__tot.game.endRun(false));
  await page.getByRole('button', { name: 'Spend essence on talents' }).click();
  await page.getByRole('button', { name: /Play again/ }).waitFor();
  assert.deepEqual(errors, []);
  console.log('Expansion gameplay and screen checks passed. No checkout was invoked.');
} finally { await browser.close(); }
