import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { chromium } from 'playwright-core';
const manifest = JSON.parse(await fs.readFile('src/game/sound/manifest.json', 'utf8'));
for (const track of manifest.music) {
  const file = `public/audio/music/${track.id}.mp3`;
  const ours = await fs.readFile(file), original = await fs.readFile(path.join('../Heavy-Metal-GP', file));
  assert.equal(crypto.createHash('sha256').update(ours).digest('hex'), crypto.createHash('sha256').update(original).digest('hex'), track.id);
}
console.log(`${manifest.music.length} radio recordings match Heavy-Metal-GP byte-for-byte.`);
const browser = await chromium.launch({ channel: 'msedge' });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:5173/');
  await page.getByRole('button', { name: 'Go trick-or-treating' }).waitFor({ timeout: 120000 });
  await page.screenshot({ path: 'art/world/checks/expanded-title.png' });
  await page.getByRole('button', { name: /Preview expansion locally/ }).click();
  await page.getByRole('button', { name: /Play rescue campaign/ }).click();
  await page.waitForFunction(() => window.__tot?.game?.state === 'intro');
  await page.getByRole('button', { name: /skip intro/ }).waitFor();
  await page.waitForTimeout(600);
  await page.screenshot({ path: 'art/world/checks/rescue-intro.png' });
  await page.keyboard.press('Space');
  await page.waitForFunction(() => window.__tot.game.state === 'play');
  await page.evaluate(() => { const g = window.__tot.game; g.p.invuln = 999; g.state = 'levelup'; g.choose('sugar'); g.state = 'levelup'; g.choose('sugar'); g.state = 'levelup'; g.choose('walkie'); });
  await page.keyboard.press('i');
  await page.getByRole('dialog', { name: 'Run inventory' }).waitFor();
  await page.getByRole('textbox', { name: 'Search collected treats' }).fill('friend');
  assert.equal(await page.getByRole('dialog').count(), 1);
  await page.getByRole('textbox', { name: 'Search collected treats' }).fill('');
  await page.screenshot({ path: 'art/world/checks/stacked-inventory.png' });
  assert.equal(await page.evaluate(() => window.__tot.game.scrolls.sugar), 2);
  await page.getByRole('button', { name: 'Close inventory' }).click();
  await page.evaluate(() => { const g = window.__tot.game; const f = g.friends[0]; f.status = 'rescued'; g.activeFriend = f.hero; g.state = 'pause'; });
  await page.getByRole('button', { name: /Friends.*guns/ }).click();
  await page.getByRole('button', { name: 'Swap gun 1' }).first().waitFor();
  await page.screenshot({ path: 'art/world/checks/companion-loadout.png' });
  const audio = await page.evaluate(async () => {
    const { gameAudio, SFX_LOW_PASS_HZ, SFX_PLAYBACK_RATE } = await import('/src/game/audio.ts');
    const { radio } = await import('/src/game/sound/radio.ts');
    gameAudio.unlock(); radio.unlock();
    const ctx = gameAudio.context;
    const sounds = (await import('/src/game/sound/manifest.json')).default.sfx;
    const decoded = [];
    for (const sound of sounds) {
      const response = await fetch(`/audio/sfx/${sound.id}.mp3`); if (!response.ok) throw new Error(`Missing ${sound.id}`);
      const buffer = await ctx.decodeAudioData(await response.arrayBuffer());
      if (!(buffer.duration >= 0.3 && buffer.duration < 15)) throw new Error(`Invalid ${sound.id} duration`);
      decoded.push({ id: sound.id, seconds: Number(buffer.duration.toFixed(2)) });
    }
    const low = ctx.createBiquadFilter(); low.type = 'lowpass'; low.frequency.value = SFX_LOW_PASS_HZ; low.Q.value = .5;
    const frequencies = new Float32Array([100, 1000, 4000, 8000]), gain = new Float32Array(4), phase = new Float32Array(4);
    low.getFrequencyResponse(frequencies, gain, phase);
    const decks = radio.decks.filter(Boolean);
    await Promise.all(decks.map(deck => deck.play().catch(() => undefined)));
    return { decoded, highAttenuationDb: 20 * Math.log10(gain[2]), lowPassHz: SFX_LOW_PASS_HZ, playbackRate: SFX_PLAYBACK_RATE, radioLoaded: decks.some(deck => deck.readyState >= 2 && !deck.paused), playing: radio.snapshot().playing };
  });
  console.log(JSON.stringify(audio, null, 2));
  assert.equal(audio.decoded.length, manifest.sfx.length); assert.equal(audio.lowPassHz, 700); assert.equal(audio.playbackRate, 1); assert.ok(audio.highAttenuationDb < -20); assert.ok(audio.playing && audio.radioLoaded);
  await page.evaluate(() => window.__tot.game.endRun(false));
  await page.getByRole('button', { name: 'Spend essence on talents' }).waitFor();
  await page.waitForTimeout(1400);
  await page.screenshot({ path: 'art/world/checks/death-essence-summary.png' });
  await page.getByRole('button', { name: 'Spend essence on talents' }).click();
  await page.getByRole('button', { name: /Play again with these talents/ }).waitFor();
  await page.screenshot({ path: 'art/world/checks/post-run-talents.png' });
  const balance = await page.evaluate(() => window.__tot.game.save.soul);
  await page.getByRole('button', { name: /Invest/ }).click();
  assert.equal(await page.evaluate(() => window.__tot.game.save.talents.sharp), 1);
  assert.equal(await page.evaluate(() => window.__tot.game.save.soul), balance - 15);
  await page.getByRole('button', { name: /Play again with these talents/ }).click();
  await page.waitForFunction(() => window.__tot.game.state === 'intro');
  assert.ok(await page.evaluate(() => window.__tot.game.stats.dmg > 1.15));
  assert.deepEqual(errors, []);
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await mobile.goto('http://127.0.0.1:5173/');
  await mobile.getByRole('button', { name: 'Go trick-or-treating' }).waitFor({ timeout: 120000 });
  await mobile.getByRole('button', { name: 'Go trick-or-treating' }).scrollIntoViewIfNeeded();
  await mobile.screenshot({ path: 'art/world/checks/mobile-title.png' });
  await mobile.getByRole('button', { name: 'Go trick-or-treating' }).click();
  await mobile.waitForFunction(() => window.__tot?.game);
  await mobile.keyboard.press('i');
  await mobile.getByRole('dialog', { name: 'Run inventory' }).waitFor();
  await mobile.screenshot({ path: 'art/world/checks/mobile-inventory.png' });
  console.log(`Campaign opening, stacked inventory, companion menu, replay, radio playback, all ${manifest.sfx.length} sounds and mobile screens passed.`);
} finally { await browser.close(); }
